// src/utils/errors/ErrorTypes.js

/**
 * أنواع الأخطاء المستخدمة في التطبيق
 * يساعد هذا التصنيف في تحديد نوع الخطأ ومعالجته بطريقة مناسبة
 */

// أخطاء المصادقة
export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  REGISTRATION_FAILED: 'AUTH_REGISTRATION_FAILED',
  INVALID_RESET_TOKEN: 'AUTH_INVALID_RESET_TOKEN',
  PASSWORD_RESET_FAILED: 'AUTH_PASSWORD_RESET_FAILED',
  REQUIRED_LOGIN: 'AUTH_REQUIRED_LOGIN',
};

// أخطاء الشبكة
export const NETWORK_ERRORS = {
  CONNECTION_FAILED: 'NETWORK_CONNECTION_FAILED',
  TIMEOUT: 'NETWORK_TIMEOUT',
  SERVER_UNAVAILABLE: 'NETWORK_SERVER_UNAVAILABLE',
  REQUEST_ABORTED: 'NETWORK_REQUEST_ABORTED',
  CORS_ERROR: 'NETWORK_CORS_ERROR',
};

// أخطاء الخادم
export const SERVER_ERRORS = {
  INTERNAL_ERROR: 'SERVER_INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVER_SERVICE_UNAVAILABLE',
  MAINTENANCE: 'SERVER_MAINTENANCE',
  INVALID_RESPONSE: 'SERVER_INVALID_RESPONSE',
  RATE_LIMITED: 'SERVER_RATE_LIMITED',
};

// أخطاء البيانات
export const DATA_ERRORS = {
  NOT_FOUND: 'DATA_NOT_FOUND',
  VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  DUPLICATE_ENTRY: 'DATA_DUPLICATE_ENTRY',
  ALREADY_EXISTS: 'DATA_ALREADY_EXISTS',
  INVALID_FORMAT: 'DATA_INVALID_FORMAT',
  REQUIRED_FIELD_MISSING: 'DATA_REQUIRED_FIELD_MISSING',
};

// أخطاء الدورات التعليمية
export const COURSE_ERRORS = {
  ENROLLMENT_FAILED: 'COURSE_ENROLLMENT_FAILED',
  ALREADY_ENROLLED: 'COURSE_ALREADY_ENROLLED',
  ACCESS_DENIED: 'COURSE_ACCESS_DENIED',
  CONTENT_LOCKED: 'COURSE_CONTENT_LOCKED',
  PROGRESS_UPDATE_FAILED: 'COURSE_PROGRESS_UPDATE_FAILED',
};

// أخطاء الامتحانات
export const EXAM_ERRORS = {
  REGISTRATION_FAILED: 'EXAM_REGISTRATION_FAILED',
  ALREADY_REGISTERED: 'EXAM_ALREADY_REGISTERED',
  START_FAILED: 'EXAM_START_FAILED',
  SUBMIT_FAILED: 'EXAM_SUBMIT_FAILED',
  TIME_EXPIRED: 'EXAM_TIME_EXPIRED',
  ALREADY_SUBMITTED: 'EXAM_ALREADY_SUBMITTED',
  ANSWER_SUBMIT_FAILED: 'EXAM_ANSWER_SUBMIT_FAILED',
};

// أخطاء الدفع
export const PAYMENT_ERRORS = {
  TRANSACTION_FAILED: 'PAYMENT_TRANSACTION_FAILED',
  INSUFFICIENT_FUNDS: 'PAYMENT_INSUFFICIENT_FUNDS',
  ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  INVALID_PAYMENT_METHOD: 'PAYMENT_INVALID_PAYMENT_METHOD',
  PAYMENT_CANCELED: 'PAYMENT_CANCELED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  REFUND_FAILED: 'PAYMENT_REFUND_FAILED',
};

// أخطاء الملفات
export const FILE_ERRORS = {
  UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  INVALID_TYPE: 'FILE_INVALID_TYPE',
  CORRUPT_FILE: 'FILE_CORRUPT_FILE',
  ACCESS_DENIED: 'FILE_ACCESS_DENIED',
};

// أخطاء أخرى
export const OTHER_ERRORS = {
  UNKNOWN_ERROR: 'OTHER_UNKNOWN_ERROR',
  FEATURE_UNAVAILABLE: 'OTHER_FEATURE_UNAVAILABLE',
  UNAUTHORIZED_ACTION: 'OTHER_UNAUTHORIZED_ACTION',
  OPERATION_ABORTED: 'OTHER_OPERATION_ABORTED',
  INVALID_STATE: 'OTHER_INVALID_STATE',
};

// تصدير جميع أنواع الأخطاء مجمعة
export const ERROR_TYPES = {
  ...AUTH_ERRORS,
  ...NETWORK_ERRORS,
  ...SERVER_ERRORS,
  ...DATA_ERRORS,
  ...COURSE_ERRORS,
  ...EXAM_ERRORS,
  ...PAYMENT_ERRORS,
  ...FILE_ERRORS,
  ...OTHER_ERRORS,
};

export default ERROR_TYPES;